% inputData=[F0_cpYFP... 
%     dF_F0_cpYFP... 
%     F0_TMRM... 
%     dF_F0_TMRM... 
%     time1_cpYFP... 
%     time1_TMRM... 
%     time2_cpYFP... 
%     time2_TMRM];
% 
% clear F0_cpYFP... 
%     dF_F0_cpYFP... 
%     F0_TMRM... 
%     dF_F0_TMRM... 
%     time1_cpYFP... 
%     time1_TMRM... 
%     time2_cpYFP... 
%     time2_TMRM
% 
% target=zeros(size(inputData,1),9);
% for id=1:size(target,1)
%     target(id,cleanedFlash(id,15)/5)=1;
% end

inputData=allTMRMTraces;
target=zeros(size(inputData,1),9);
for id=1:size(target,1)
    target(id,allROIs(id,5)/5)=1;
end

inputData1=inputData(1:2:end,:);
target1=target(1:2:end,:);

inputData2=inputData(2:2:end,:);
target2=target(2:2:end,:);
